
run:
  runs-on:
    ubuntu-24.04: 2
    ubuntu-22.04: 1
  runtime:
    podman: 4
    sudo podman: 1
    docker rootless: 3
    docker: 2
  readonly:
    --read-only: 3
    "": null
  ca:
    "": 3
    --external-ca: 1
  volume:
    freeipa-data: 1
    "": null
  count: 19
  exclude:
    # Workaround https://github.com/freeipa/freeipa-container/issues/660
    - runtime: sudo podman
      runs-on: ubuntu-22.04

test-upgrade:
  runs-on:
    ubuntu-24.04: 2
    ubuntu-22.04: 1
  runtime:
    podman: 3
    docker: 1
  upgrade-to-from:
    fedora-rawhide:
      - fedora-41
    fedora-41:
      - fedora-41
      - fedora-40
    fedora-40:
      - fedora-40
      - fedora-39
    almalinux-8:
      - centos-8-certs-updated-data
    rocky-8:
      - centos-8-certs-updated-data
  count: 7

k8s:
  runs-on:
    ubuntu-24.04: 2
    ubuntu-22.04: 1
  kubernetes:
    k3s: 1
  runtime:
    cri-o: 1
    docker: 1
  count: 9

