
run:
  runs-on:
    ubuntu-24.04: 2
    ubuntu-22.04: 1
  runtime:
    podman: 4
    sudo podman: 1
    docker rootless: 3
    docker: 2
  readonly:
    --read-only: 3
    "": 1
  ca:
    "": 3
    --external-ca: 1
  volume:
    freeipa-data: 1
    "": 1
  count: 23

test-upgrade:
  runs-on:
    ubuntu-24.04: 2
    ubuntu-22.04: 1
  runtime:
    podman: 3
    docker: 1
  upgrade-to-from:
    fedora-rawhide:
      - fedora-41
    fedora-41:
      - fedora-41
      - fedora-40
    fedora-40:
      - fedora-40
      - fedora-39
    almalinux-8:
      - centos-8-certs-updated-data
    rocky-8:
      - centos-8-certs-updated-data
  count: 7

k3s:
  count: 5

